#!/usr/local/bin/python

import argparse
from supergsl.core.pipeline import CompilerPipeline
import pprint


def main():

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "input_file",
        help="The input source code file to process",
        type=str)

    args = parser.parse_args()

    print('Compiling "%s".' % args.input_file)
    pipeline = CompilerPipeline()
    with open(args.input_file, 'r') as input_file_fp:
        result = pipeline.compile(input_file_fp.read())

    pprint.pprint(result)


if __name__ == "__main__":
    main()
