# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import supergsl.grpc.stubs.sgsl_pb2 as sgsl__pb2


class SuperGSLCompilerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCompilerSession = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/CreateCompilerSession',
                request_serializer=sgsl__pb2.CreateCompilerSessionRequest.SerializeToString,
                response_deserializer=sgsl__pb2.CreateCompilerSessionResult.FromString,
                )
        self.DestroyCompilerSession = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/DestroyCompilerSession',
                request_serializer=sgsl__pb2.DestroyCompilerSessionRequest.SerializeToString,
                response_deserializer=sgsl__pb2.DestroyCompilerSessionResult.FromString,
                )
        self.Compile = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/Compile',
                request_serializer=sgsl__pb2.CompileRequest.SerializeToString,
                response_deserializer=sgsl__pb2.CompileResult.FromString,
                )
        self.ListSymbolTable = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/ListSymbolTable',
                request_serializer=sgsl__pb2.ListSymbolTableRequest.SerializeToString,
                response_deserializer=sgsl__pb2.ListSymbolTableResult.FromString,
                )
        self.ListSequenceStore = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/ListSequenceStore',
                request_serializer=sgsl__pb2.ListSequenceStoreRequest.SerializeToString,
                response_deserializer=sgsl__pb2.ListSequenceStoreResult.FromString,
                )
        self.GetSequenceDetail = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/GetSequenceDetail',
                request_serializer=sgsl__pb2.GetSequenceDetailRequest.SerializeToString,
                response_deserializer=sgsl__pb2.GetSequenceDetailResult.FromString,
                )
        self.GetFunctionArguments = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/GetFunctionArguments',
                request_serializer=sgsl__pb2.FunctionCallIdentifier.SerializeToString,
                response_deserializer=sgsl__pb2.MessageFunctionArguments.FromString,
                )
        self.SetFunctionReturnValue = channel.unary_unary(
                '/supergsl.SuperGSLCompiler/SetFunctionReturnValue',
                request_serializer=sgsl__pb2.FunctionReturnValue.SerializeToString,
                response_deserializer=sgsl__pb2.SetFunctionReturnValueResponse.FromString,
                )


class SuperGSLCompilerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCompilerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyCompilerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSymbolTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSequenceStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSequenceDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunctionArguments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFunctionReturnValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuperGSLCompilerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCompilerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCompilerSession,
                    request_deserializer=sgsl__pb2.CreateCompilerSessionRequest.FromString,
                    response_serializer=sgsl__pb2.CreateCompilerSessionResult.SerializeToString,
            ),
            'DestroyCompilerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyCompilerSession,
                    request_deserializer=sgsl__pb2.DestroyCompilerSessionRequest.FromString,
                    response_serializer=sgsl__pb2.DestroyCompilerSessionResult.SerializeToString,
            ),
            'Compile': grpc.unary_unary_rpc_method_handler(
                    servicer.Compile,
                    request_deserializer=sgsl__pb2.CompileRequest.FromString,
                    response_serializer=sgsl__pb2.CompileResult.SerializeToString,
            ),
            'ListSymbolTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSymbolTable,
                    request_deserializer=sgsl__pb2.ListSymbolTableRequest.FromString,
                    response_serializer=sgsl__pb2.ListSymbolTableResult.SerializeToString,
            ),
            'ListSequenceStore': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSequenceStore,
                    request_deserializer=sgsl__pb2.ListSequenceStoreRequest.FromString,
                    response_serializer=sgsl__pb2.ListSequenceStoreResult.SerializeToString,
            ),
            'GetSequenceDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSequenceDetail,
                    request_deserializer=sgsl__pb2.GetSequenceDetailRequest.FromString,
                    response_serializer=sgsl__pb2.GetSequenceDetailResult.SerializeToString,
            ),
            'GetFunctionArguments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunctionArguments,
                    request_deserializer=sgsl__pb2.FunctionCallIdentifier.FromString,
                    response_serializer=sgsl__pb2.MessageFunctionArguments.SerializeToString,
            ),
            'SetFunctionReturnValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFunctionReturnValue,
                    request_deserializer=sgsl__pb2.FunctionReturnValue.FromString,
                    response_serializer=sgsl__pb2.SetFunctionReturnValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'supergsl.SuperGSLCompiler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuperGSLCompiler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCompilerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/CreateCompilerSession',
            sgsl__pb2.CreateCompilerSessionRequest.SerializeToString,
            sgsl__pb2.CreateCompilerSessionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyCompilerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/DestroyCompilerSession',
            sgsl__pb2.DestroyCompilerSessionRequest.SerializeToString,
            sgsl__pb2.DestroyCompilerSessionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Compile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/Compile',
            sgsl__pb2.CompileRequest.SerializeToString,
            sgsl__pb2.CompileResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSymbolTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/ListSymbolTable',
            sgsl__pb2.ListSymbolTableRequest.SerializeToString,
            sgsl__pb2.ListSymbolTableResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSequenceStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/ListSequenceStore',
            sgsl__pb2.ListSequenceStoreRequest.SerializeToString,
            sgsl__pb2.ListSequenceStoreResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSequenceDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/GetSequenceDetail',
            sgsl__pb2.GetSequenceDetailRequest.SerializeToString,
            sgsl__pb2.GetSequenceDetailResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFunctionArguments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/GetFunctionArguments',
            sgsl__pb2.FunctionCallIdentifier.SerializeToString,
            sgsl__pb2.MessageFunctionArguments.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetFunctionReturnValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/supergsl.SuperGSLCompiler/SetFunctionReturnValue',
            sgsl__pb2.FunctionReturnValue.SerializeToString,
            sgsl__pb2.SetFunctionReturnValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
