# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgsl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgsl.proto',
  package='supergsl',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nsgsl.proto\x12\x08supergsl\",\n\x16\x46unctionCallIdentifier\x12\x12\n\nidentifier\x18\x01 \x01(\t\"(\n\x18MessageFunctionArguments\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x13\x46unctionReturnValue\x12\r\n\x05value\x18\x01 \x01(\t\"2\n\x1eSetFunctionReturnValueResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\xd7\x01\n\x10\x43ompilerFunction\x12^\n\x14GetFunctionArguments\x12 .supergsl.FunctionCallIdentifier\x1a\".supergsl.MessageFunctionArguments\"\x00\x12\x63\n\x16SetFunctionReturnValue\x12\x1d.supergsl.FunctionReturnValue\x1a(.supergsl.SetFunctionReturnValueResponse\"\x00\x42\x03\x90\x01\x01\x62\x06proto3'
)




_FUNCTIONCALLIDENTIFIER = _descriptor.Descriptor(
  name='FunctionCallIdentifier',
  full_name='supergsl.FunctionCallIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='supergsl.FunctionCallIdentifier.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_MESSAGEFUNCTIONARGUMENTS = _descriptor.Descriptor(
  name='MessageFunctionArguments',
  full_name='supergsl.MessageFunctionArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='supergsl.MessageFunctionArguments.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=110,
)


_FUNCTIONRETURNVALUE = _descriptor.Descriptor(
  name='FunctionReturnValue',
  full_name='supergsl.FunctionReturnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='supergsl.FunctionReturnValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=148,
)


_SETFUNCTIONRETURNVALUERESPONSE = _descriptor.Descriptor(
  name='SetFunctionReturnValueResponse',
  full_name='supergsl.SetFunctionReturnValueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='received', full_name='supergsl.SetFunctionReturnValueResponse.received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['FunctionCallIdentifier'] = _FUNCTIONCALLIDENTIFIER
DESCRIPTOR.message_types_by_name['MessageFunctionArguments'] = _MESSAGEFUNCTIONARGUMENTS
DESCRIPTOR.message_types_by_name['FunctionReturnValue'] = _FUNCTIONRETURNVALUE
DESCRIPTOR.message_types_by_name['SetFunctionReturnValueResponse'] = _SETFUNCTIONRETURNVALUERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FunctionCallIdentifier = _reflection.GeneratedProtocolMessageType('FunctionCallIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONCALLIDENTIFIER,
  '__module__' : 'sgsl_pb2'
  # @@protoc_insertion_point(class_scope:supergsl.FunctionCallIdentifier)
  })
_sym_db.RegisterMessage(FunctionCallIdentifier)

MessageFunctionArguments = _reflection.GeneratedProtocolMessageType('MessageFunctionArguments', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEFUNCTIONARGUMENTS,
  '__module__' : 'sgsl_pb2'
  # @@protoc_insertion_point(class_scope:supergsl.MessageFunctionArguments)
  })
_sym_db.RegisterMessage(MessageFunctionArguments)

FunctionReturnValue = _reflection.GeneratedProtocolMessageType('FunctionReturnValue', (_message.Message,), {
  'DESCRIPTOR' : _FUNCTIONRETURNVALUE,
  '__module__' : 'sgsl_pb2'
  # @@protoc_insertion_point(class_scope:supergsl.FunctionReturnValue)
  })
_sym_db.RegisterMessage(FunctionReturnValue)

SetFunctionReturnValueResponse = _reflection.GeneratedProtocolMessageType('SetFunctionReturnValueResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETFUNCTIONRETURNVALUERESPONSE,
  '__module__' : 'sgsl_pb2'
  # @@protoc_insertion_point(class_scope:supergsl.SetFunctionReturnValueResponse)
  })
_sym_db.RegisterMessage(SetFunctionReturnValueResponse)


DESCRIPTOR._options = None

_COMPILERFUNCTION = _descriptor.ServiceDescriptor(
  name='CompilerFunction',
  full_name='supergsl.CompilerFunction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=203,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFunctionArguments',
    full_name='supergsl.CompilerFunction.GetFunctionArguments',
    index=0,
    containing_service=None,
    input_type=_FUNCTIONCALLIDENTIFIER,
    output_type=_MESSAGEFUNCTIONARGUMENTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetFunctionReturnValue',
    full_name='supergsl.CompilerFunction.SetFunctionReturnValue',
    index=1,
    containing_service=None,
    input_type=_FUNCTIONRETURNVALUE,
    output_type=_SETFUNCTIONRETURNVALUERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPILERFUNCTION)

DESCRIPTOR.services_by_name['CompilerFunction'] = _COMPILERFUNCTION

CompilerFunction = service_reflection.GeneratedServiceType('CompilerFunction', (_service.Service,), dict(
  DESCRIPTOR = _COMPILERFUNCTION,
  __module__ = 'sgsl_pb2'
  ))

CompilerFunction_Stub = service_reflection.GeneratedServiceStubType('CompilerFunction_Stub', (CompilerFunction,), dict(
  DESCRIPTOR = _COMPILERFUNCTION,
  __module__ = 'sgsl_pb2'
  ))


# @@protoc_insertion_point(module_scope)
